import React, {Component} from 'react'
import {PageHeader} from 'react-bootstrap'

const styles = {
  textContainer: {
    marginLeft: '40px',
    marginTop: '30px'
  },
  textBlock: {
    maxWidth: '800px',
    marginLeft: '40px'
  },
  subHeader: {
    marginLeft: '20px'
  }
};


const privacyPolicy = ({}) => (
  <div>
    <PageHeader style={{position: 'relative', paddingLeft: '40px'}}>AppTab</PageHeader>
    <div style={styles.textContainer}>
      <h1>Privacy</h1>
      <h3 style={styles.subHeader}>Credit Cards</h3>
      <div style={styles.textBlock}>
        All of our credit cards are processed by <a href="https://www.stripe.com">Stripe</a>, the largest online payments processor.
        This means that the only part of your credit card information that ever touches our servers is the last four
        digits, card type, and expiration date. The only reason we save this information is so that you can identify
        what credit card you want to use in the app.
        We are fully PCI compliant and will never share this information with any third parties.
      </div>
      <h3 style={styles.subHeader}>Personally Identifiable Information</h3>
      <div style={styles.textBlock}>
        We use your phone number, email address, and first name as part of the registration process and to verify your
        identity. We do not share this information with anyone.
      </div>
      <h3 style={styles.subHeader}>App Generated Data</h3>
      <div style={styles.textBlock}>
        All the data generated by using the app itself (i.e. in app purchases, navigation, registration, login, etc.) is
        the property of AppTab Inc. and we reserve the right to use that data in any capacity. Mostly we use this in
        creating reports for restaurants and internal analytics.
      </div>
      <h3 style={styles.subHeader}>Phone Data</h3>
      <div style={styles.textBlock}>
        We do not collect any data on your phone other than what type it is. That means that we don't access your
        contacts, pictures, camera, microphone, location data, installed apps, etc. We care about
        improving your restaurant experience, not your personal life.
      </div>
      <h3 style={styles.subHeader}>Third Party Integrations</h3>
      <div style={styles.textBlock}>
        We integrate with Facebook to provide you with a better login/registration experience. We don't access
        any information other than your name, phone number, and email address.
      </div>
    </div>
  </div>
);

export default privacyPolicy