---
Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: "apptab.io"
  CloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - apptab.io
        - www.apptab.io
        PriceClass: PriceClass_100
        DefaultRootObject: /index.html
        CustomErrorResponses:
        - ErrorCode: "404"
          ResponsePagePath: /index.html
          ResponseCode: "200"
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - POST
          - OPTIONS
          - HEAD
          - DELETE
          - PUT
          - PATCH
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
          TargetOriginId: apptabOrigin
          ViewerProtocolPolicy: redirect-to-https
        Origins:
        - DomainName: apptab.io.s3.amazonaws.com
          Id: apptabOrigin
          S3OriginConfig:
            OriginAccessIdentity: origin-access-identity/cloudfront/EOGFP725PDDYK
        ViewerCertificate:
          AcmCertificateArn:
            Ref: Certificate
          SslSupportMethod: sni-only