---
Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: "apptab.io"
  CloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - apptab.io
        - www.apptab.io
        PriceClass: PriceClass_100
        DefaultRootObject: /index.html
        CustomErrorResponses:
        - ErrorCode: "404"
          ResponsePagePath: /index.html
          ResponseCode: "200"
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - POST
          - OPTIONS
          - HEAD
          - DELETE
          - PUT
          - PATCH
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
          TargetOriginId: apptabOrigin
          ViewerProtocolPolicy: redirect-to-https
        Origins:
        - DomainName: apptab.io.s3.amazonaws.com
          Id: apptabOrigin
          S3OriginConfig:
            OriginAccessIdentity: origin-access-identity/cloudfront/EOGFP725PDDYK
        ViewerCertificate:
          AcmCertificateArn:
            Ref: Certificate
          SslSupportMethod: sni-only
  TestCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: "apptabtest.io"
  TestCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - apptabtest.io
        - www.apptabtest.io
        PriceClass: PriceClass_100
        DefaultRootObject: /index.html
        CustomErrorResponses:
        - ErrorCode: "404"
          ResponsePagePath: /index.html
          ResponseCode: "200"
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - POST
          - OPTIONS
          - HEAD
          - DELETE
          - PUT
          - PATCH
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
          TargetOriginId: apptabtestOrigin
          ViewerProtocolPolicy: redirect-to-https
        Origins:
        - DomainName: apptabtest.io.s3.amazonaws.com
          Id: apptabtestOrigin
          S3OriginConfig:
            OriginAccessIdentity: origin-access-identity/cloudfront/E27B6OZXAI6B8U
        ViewerCertificate:
          AcmCertificateArn:
            Ref: TestCertificate
          SslSupportMethod: sni-only
        WebACLId:
          Ref: TestWebACL
  TestWebACL:
    Type: AWS::WAF::WebACL
    Properties:
      DefaultAction:
        Type: BLOCK
      MetricName: AppTabTestMetric
      Name: AppTabTestACL
      Rules:
      - Action:
          Type: ALLOW
        Priority: 1
        RuleId:
          Ref: WhiteListRule
  WhiteListRule:
    Type: AWS::WAF::Rule
    Properties:
      Name: WhiteListRule
      MetricName: AppTabTestWhiteListMetric
      Predicates:
      - DataId:
          Ref: IPWhiteList
        Negated: false
        Type: IPMatch
  IPWhiteList:
    Type: AWS::WAF::IPSet
    Properties:
      IPSetDescriptors:
      - Type: IPV4
        Value: 73.202.73.133/32
      Name: WhiteList
