---
Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: "PublicRead"
      BucketName: apptab.io
      WebsiteConfiguration:
        IndexDocument: index.html
        RoutingRules:
        - RedirectRule:
            HostName: apptab.io
            Protocol: http
            ReplaceKeyPrefixWith: "#!/"
          RoutingRuleCondition:
            HttpErrorCodeReturnedEquals: "404"
  RedirectBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: www.apptab.io
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: apptab.io
          Protocol: http
  SiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: SiteBucket
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal: "*"
          Action: s3:GetObject
          Resource:
            Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - Ref: SiteBucket
              - "/*"
  CloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        PriceClass: PriceClass_100
        CustomErrorResponse:
          ErrorCode: "404"
          ResponsePagePath: /index.html
          RespnseCode: "200"
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - POST
          - OPTIONS
          - HEAD
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
          TargetOriginId: 1
        Origins:
        - DomainName:
            Fn::GetAtt: SiteBucket
          Id: 1
          S3OriginConfig:
            OriginAccessIdentity: