---
Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: "PublicRead"
      BucketName: apptab.io
      WebsiteConfiguration:
        IndexDocument: index.html
  RedirectBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: www.apptab.io
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: apptab.io
          Protocol: http
  SiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: SiteBucket
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal: "*"
          Action: s3:GetObject
          Resource:
            Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - Ref: SiteBucket
              - "/*"
  CloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - apptab.io
        - www.apptab.io
        PriceClass: PriceClass_100
        DefaultRootObject: /index.html
        CustomErrorResponses:
        - ErrorCode: "404"
          ResponsePagePath: /index.html
          ResponseCode: "200"
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - POST
          - OPTIONS
          - HEAD
          - DELETE
          - PUT
          - PATCH
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
          TargetOriginId: apptabOrigin
          ViewerProtocolPolicy: redirect-to-https
        Origins:
        - DomainName:
            Fn::GetAtt: [SiteBucket, DomainName]
          Id: apptabOrigin
          S3OriginConfig:
            OriginAccessIdentity: origin-access-identity/cloudfront/EOGFP725PDDYK
        ViewerCertificate:
          AcmCertificateArn:
            Ref: Certificate
          SslSupportMethod: vip
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: "apptab.io"
